### ISSUE TITLE
adding "group" lines for the ICE plot

### ISSUE THREAD

**Issue by ilyalipkovich** [kapelner/ICEbox#11]
One useful feature of the ice plot is assigning colors to individual lines based on levels of another variable (potentially interacting with the variable plotted on X-axis). See an example in ICEbox manual for plot.ice function (p. 12):

## color the curves by high and low values of 'rm'.
# First create an indicator variable which is 1 if the number of
# rooms is greater than the median:
median_rm = median(X$rm)
bhd.ice$Xice$I_rm = ifelse(bhd.ice$Xice$rm > median_rm, 1, 0)
plot(bhd.ice, frac_to_plot = 1, centered = TRUE, prop_range_y = TRUE,
x_quantile = T, plot_orig_pts_preds = T, color_by = "I_rm")

I think it would be natural to have an option of adding thick lines on the graph representing the averages of individual curves (ICEs) for the groups defined by color (in this example defined by I_rm, but could be based on multiple levels. This would make it easier to see possible interaction effects (like we do for usual interaction  plots, say based on simple linear models with interactions)

**Comment by kapelner** [comment]
There's no way to do this natively with ICEbox functions, but because all the raw data is returned in the `ice` function, it's not so bad:

```
pacman::p_load(ICEbox, dplyr, randomForest)

X = MASS::Boston %>% select(-medv)
y = MASS::Boston$medv

rf_mod = randomForest(X, y)

ice_obj = ice(rf_mod, X, y, "lstat")
plot(ice_obj, x_quantile = TRUE, centered = TRUE, color_by = "chas")
#get the PDP's of the color_by variable
pdpchas0 = apply(ice_obj$ice_curves[X$chas == 0, ], 2, mean)
pdpchas1 = apply(ice_obj$ice_curves[X$chas == 1, ], 2, mean)
grid = ice_obj$gridpts
#if x_quantile is TRUE
ecdf_fcn = ecdf(grid)
grid = ecdf_fcn(grid)
#if centered...and centered at 0...
pdpchas0 = pdpchas0 - pdpchas0[1]
pdpchas1 = pdpchas1 - pdpchas1[1]
#o/t go straight here (you can customize the thickness and colors below)
points(grid, pdpchas0, col = "black", type = "l", lwd = 9)
points(grid, pdpchas0, col = "firebrick3", type = "l", lwd = 3)
points(grid, pdpchas1, col = "black", type = "l", lwd = 9)
points(grid, pdpchas1, col = "dodgerblue3", type = "l", lwd = 3)
#this code can also be vectorized for all levels of the color_by variable
```

![Rplot](https://user-images.githubusercontent.com/658168/88301936-39e9a280-ccd3-11ea-94bf-f35d3d7669df.png)


Apologies this is not in ggplot2! ICEbox actually predates the popularization of tidyverse (if you can believe it)...
