### ISSUE TITLE
Error when predict function returns an object with multiple classes.

### ISSUE THREAD

**Issue by davidaarmstrong** [kapelner/ICEbox#13]
When I use `ice()` with a MARS model (estimated with `earth()`), the default predictor function returns a matrix (even if it is only a single column).  When this happens, `ice()` returns an error. 

``` r
library(ICEbox)
#> Loading required package: sfsmisc
library(earth)
#> Loading required package: Formula
#> Loading required package: plotmo
#> Loading required package: plotrix
#> Loading required package: TeachingDemos
#> Registered S3 method overwritten by 'TeachingDemos':
#>   method    from  
#>   plot.dice ICEbox
#> 
#> Attaching package: 'TeachingDemos'
#> The following object is masked from 'package:ICEbox':
#> 
#>     dice
mtcars <- na.omit(mtcars)
mod <- earth(qsec ~ hp + wt + drat + cyl, data=mtcars)

ice(mod, mtcars[,c("hp", "wt", "drat", "cyl")], mtcars$qsec, "wt")
#> Error in if (class(actual_prediction) == "factor") {: the condition has length > 1
```

This is because the class of earth predictions is `c("matrix", "array")`.  In general, it might be safer to use `if(inherits(actual_prediction, "factor"))` as this works whether or not the object has multiple classes.  If I modify the prediction function to return a vector (which has a single class) rather than a matrix, everything works alright: 

```r
earth_pred <- function(object, newdata, ...){
  preds <- predict(object, newdata, type="response", ...)
  if(ncol(preds) == 1){
    preds <- c(preds)
  }
  preds
}

ice(mod, mtcars[,c("hp", "wt", "drat", "cyl")], mtcars$qsec, "wt", predictfcn = earth_pred)
#> .............................
```

<sup>Created on 2022-06-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I recognize that the documentation says that the prediction function should return an `N`-length vector, so this isn't really a bug, but a slight modification to the code would make it work in other cases, too.  I forked the repo and made the changes.  I can submit a pull request if you'd like.

**Comment by kapelner** [comment]
You are right - you need to code a custom predict function. We won't code
support for every modeling package.

**Comment by davidaarmstrong** [comment]
OK, that's fine.  I'm not saying that you should actively support every modelling function, just that if you checked for inheritance in a more flexible way (e.g., `inherits(actual_prediction, "factor")` or `is(actual_prediction, "factor")`) instead of using `class(actual_prediction) == "factor"`, which fails with an error for any predict method that returns an object with a vector of classes, that your package would naturally support more prediction functions without you having to do so explicitly.  It's obviously your package, though, and if you don't want to do that, it's fine.

**Comment by kapelner** [comment]
I agree. I actually changed all the class checks to `inherits` as this is now recommended by CRAN. Should be released on CRAN shortly.
